/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRecurrencesRouteImport } from './routes/_authenticated/recurrences'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated/partners'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedInvestmentsRouteImport } from './routes/_authenticated/investments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedFiscalIndexRouteImport } from './routes/_authenticated/fiscal/index'
import { Route as AuthenticatedBudgetsIndexRouteImport } from './routes/_authenticated/budgets/index'
import { Route as ApiPublicNotaasWebhookRouteImport } from './routes/api/public/notaas-webhook'
import { Route as AuthenticatedReportsInadimplenciaRouteImport } from './routes/_authenticated/reports/inadimplencia'
import { Route as AuthenticatedReportsFluxoRouteImport } from './routes/_authenticated/reports/fluxo'
import { Route as AuthenticatedReportsFixosRouteImport } from './routes/_authenticated/reports/fixos'
import { Route as AuthenticatedReportsFaturamentoRouteImport } from './routes/_authenticated/reports/faturamento'
import { Route as AuthenticatedReportsConversaoRouteImport } from './routes/_authenticated/reports/conversao'
import { Route as AuthenticatedReportsClientesRouteImport } from './routes/_authenticated/reports/clientes'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders/$id'
import { Route as AuthenticatedFiscalNovaRouteImport } from './routes/_authenticated/fiscal/nova'
import { Route as AuthenticatedFiscalConfiguracoesRouteImport } from './routes/_authenticated/fiscal/configuracoes'
import { Route as AuthenticatedBudgetsIdRouteImport } from './routes/_authenticated/budgets/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecurrencesRoute =
  AuthenticatedRecurrencesRouteImport.update({
    id: '/recurrences',
    path: '/recurrences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvestmentsRoute =
  AuthenticatedInvestmentsRouteImport.update({
    id: '/investments',
    path: '/investments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFiscalIndexRoute =
  AuthenticatedFiscalIndexRouteImport.update({
    id: '/fiscal/',
    path: '/fiscal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBudgetsIndexRoute =
  AuthenticatedBudgetsIndexRouteImport.update({
    id: '/budgets/',
    path: '/budgets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicNotaasWebhookRoute = ApiPublicNotaasWebhookRouteImport.update({
  id: '/api/public/notaas-webhook',
  path: '/api/public/notaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsInadimplenciaRoute =
  AuthenticatedReportsInadimplenciaRouteImport.update({
    id: '/reports/inadimplencia',
    path: '/reports/inadimplencia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsFluxoRoute =
  AuthenticatedReportsFluxoRouteImport.update({
    id: '/reports/fluxo',
    path: '/reports/fluxo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsFixosRoute =
  AuthenticatedReportsFixosRouteImport.update({
    id: '/reports/fixos',
    path: '/reports/fixos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsFaturamentoRoute =
  AuthenticatedReportsFaturamentoRouteImport.update({
    id: '/reports/faturamento',
    path: '/reports/faturamento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsConversaoRoute =
  AuthenticatedReportsConversaoRouteImport.update({
    id: '/reports/conversao',
    path: '/reports/conversao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsClientesRoute =
  AuthenticatedReportsClientesRouteImport.update({
    id: '/reports/clientes',
    path: '/reports/clientes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFiscalNovaRoute = AuthenticatedFiscalNovaRouteImport.update({
  id: '/fiscal/nova',
  path: '/fiscal/nova',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFiscalConfiguracoesRoute =
  AuthenticatedFiscalConfiguracoesRouteImport.update({
    id: '/fiscal/configuracoes',
    path: '/fiscal/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBudgetsIdRoute = AuthenticatedBudgetsIdRouteImport.update({
  id: '/budgets/$id',
  path: '/budgets/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/investments': typeof AuthenticatedInvestmentsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/recurrences': typeof AuthenticatedRecurrencesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/budgets/$id': typeof AuthenticatedBudgetsIdRoute
  '/fiscal/configuracoes': typeof AuthenticatedFiscalConfiguracoesRoute
  '/fiscal/nova': typeof AuthenticatedFiscalNovaRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/reports/clientes': typeof AuthenticatedReportsClientesRoute
  '/reports/conversao': typeof AuthenticatedReportsConversaoRoute
  '/reports/faturamento': typeof AuthenticatedReportsFaturamentoRoute
  '/reports/fixos': typeof AuthenticatedReportsFixosRoute
  '/reports/fluxo': typeof AuthenticatedReportsFluxoRoute
  '/reports/inadimplencia': typeof AuthenticatedReportsInadimplenciaRoute
  '/api/public/notaas-webhook': typeof ApiPublicNotaasWebhookRoute
  '/budgets/': typeof AuthenticatedBudgetsIndexRoute
  '/fiscal/': typeof AuthenticatedFiscalIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/investments': typeof AuthenticatedInvestmentsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/recurrences': typeof AuthenticatedRecurrencesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/budgets/$id': typeof AuthenticatedBudgetsIdRoute
  '/fiscal/configuracoes': typeof AuthenticatedFiscalConfiguracoesRoute
  '/fiscal/nova': typeof AuthenticatedFiscalNovaRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/reports/clientes': typeof AuthenticatedReportsClientesRoute
  '/reports/conversao': typeof AuthenticatedReportsConversaoRoute
  '/reports/faturamento': typeof AuthenticatedReportsFaturamentoRoute
  '/reports/fixos': typeof AuthenticatedReportsFixosRoute
  '/reports/fluxo': typeof AuthenticatedReportsFluxoRoute
  '/reports/inadimplencia': typeof AuthenticatedReportsInadimplenciaRoute
  '/api/public/notaas-webhook': typeof ApiPublicNotaasWebhookRoute
  '/budgets': typeof AuthenticatedBudgetsIndexRoute
  '/fiscal': typeof AuthenticatedFiscalIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/investments': typeof AuthenticatedInvestmentsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/partners': typeof AuthenticatedPartnersRoute
  '/_authenticated/recurrences': typeof AuthenticatedRecurrencesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/budgets/$id': typeof AuthenticatedBudgetsIdRoute
  '/_authenticated/fiscal/configuracoes': typeof AuthenticatedFiscalConfiguracoesRoute
  '/_authenticated/fiscal/nova': typeof AuthenticatedFiscalNovaRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/reports/clientes': typeof AuthenticatedReportsClientesRoute
  '/_authenticated/reports/conversao': typeof AuthenticatedReportsConversaoRoute
  '/_authenticated/reports/faturamento': typeof AuthenticatedReportsFaturamentoRoute
  '/_authenticated/reports/fixos': typeof AuthenticatedReportsFixosRoute
  '/_authenticated/reports/fluxo': typeof AuthenticatedReportsFluxoRoute
  '/_authenticated/reports/inadimplencia': typeof AuthenticatedReportsInadimplenciaRoute
  '/api/public/notaas-webhook': typeof ApiPublicNotaasWebhookRoute
  '/_authenticated/budgets/': typeof AuthenticatedBudgetsIndexRoute
  '/_authenticated/fiscal/': typeof AuthenticatedFiscalIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/categories'
    | '/clients'
    | '/dashboard'
    | '/investments'
    | '/logs'
    | '/partners'
    | '/recurrences'
    | '/settings'
    | '/tasks'
    | '/transactions'
    | '/users'
    | '/budgets/$id'
    | '/fiscal/configuracoes'
    | '/fiscal/nova'
    | '/orders/$id'
    | '/reports/clientes'
    | '/reports/conversao'
    | '/reports/faturamento'
    | '/reports/fixos'
    | '/reports/fluxo'
    | '/reports/inadimplencia'
    | '/api/public/notaas-webhook'
    | '/budgets/'
    | '/fiscal/'
    | '/orders/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/categories'
    | '/clients'
    | '/dashboard'
    | '/investments'
    | '/logs'
    | '/partners'
    | '/recurrences'
    | '/settings'
    | '/tasks'
    | '/transactions'
    | '/users'
    | '/budgets/$id'
    | '/fiscal/configuracoes'
    | '/fiscal/nova'
    | '/orders/$id'
    | '/reports/clientes'
    | '/reports/conversao'
    | '/reports/faturamento'
    | '/reports/fixos'
    | '/reports/fluxo'
    | '/reports/inadimplencia'
    | '/api/public/notaas-webhook'
    | '/budgets'
    | '/fiscal'
    | '/orders'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/categories'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/investments'
    | '/_authenticated/logs'
    | '/_authenticated/partners'
    | '/_authenticated/recurrences'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/transactions'
    | '/_authenticated/users'
    | '/_authenticated/budgets/$id'
    | '/_authenticated/fiscal/configuracoes'
    | '/_authenticated/fiscal/nova'
    | '/_authenticated/orders/$id'
    | '/_authenticated/reports/clientes'
    | '/_authenticated/reports/conversao'
    | '/_authenticated/reports/faturamento'
    | '/_authenticated/reports/fixos'
    | '/_authenticated/reports/fluxo'
    | '/_authenticated/reports/inadimplencia'
    | '/api/public/notaas-webhook'
    | '/_authenticated/budgets/'
    | '/_authenticated/fiscal/'
    | '/_authenticated/orders/'
    | '/_authenticated/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicNotaasWebhookRoute: typeof ApiPublicNotaasWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recurrences': {
      id: '/_authenticated/recurrences'
      path: '/recurrences'
      fullPath: '/recurrences'
      preLoaderRoute: typeof AuthenticatedRecurrencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/investments': {
      id: '/_authenticated/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AuthenticatedInvestmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fiscal/': {
      id: '/_authenticated/fiscal/'
      path: '/fiscal'
      fullPath: '/fiscal/'
      preLoaderRoute: typeof AuthenticatedFiscalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budgets/': {
      id: '/_authenticated/budgets/'
      path: '/budgets'
      fullPath: '/budgets/'
      preLoaderRoute: typeof AuthenticatedBudgetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/notaas-webhook': {
      id: '/api/public/notaas-webhook'
      path: '/api/public/notaas-webhook'
      fullPath: '/api/public/notaas-webhook'
      preLoaderRoute: typeof ApiPublicNotaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/inadimplencia': {
      id: '/_authenticated/reports/inadimplencia'
      path: '/reports/inadimplencia'
      fullPath: '/reports/inadimplencia'
      preLoaderRoute: typeof AuthenticatedReportsInadimplenciaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/fluxo': {
      id: '/_authenticated/reports/fluxo'
      path: '/reports/fluxo'
      fullPath: '/reports/fluxo'
      preLoaderRoute: typeof AuthenticatedReportsFluxoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/fixos': {
      id: '/_authenticated/reports/fixos'
      path: '/reports/fixos'
      fullPath: '/reports/fixos'
      preLoaderRoute: typeof AuthenticatedReportsFixosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/faturamento': {
      id: '/_authenticated/reports/faturamento'
      path: '/reports/faturamento'
      fullPath: '/reports/faturamento'
      preLoaderRoute: typeof AuthenticatedReportsFaturamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/conversao': {
      id: '/_authenticated/reports/conversao'
      path: '/reports/conversao'
      fullPath: '/reports/conversao'
      preLoaderRoute: typeof AuthenticatedReportsConversaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/clientes': {
      id: '/_authenticated/reports/clientes'
      path: '/reports/clientes'
      fullPath: '/reports/clientes'
      preLoaderRoute: typeof AuthenticatedReportsClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fiscal/nova': {
      id: '/_authenticated/fiscal/nova'
      path: '/fiscal/nova'
      fullPath: '/fiscal/nova'
      preLoaderRoute: typeof AuthenticatedFiscalNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fiscal/configuracoes': {
      id: '/_authenticated/fiscal/configuracoes'
      path: '/fiscal/configuracoes'
      fullPath: '/fiscal/configuracoes'
      preLoaderRoute: typeof AuthenticatedFiscalConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budgets/$id': {
      id: '/_authenticated/budgets/$id'
      path: '/budgets/$id'
      fullPath: '/budgets/$id'
      preLoaderRoute: typeof AuthenticatedBudgetsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvestmentsRoute: typeof AuthenticatedInvestmentsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRoute
  AuthenticatedRecurrencesRoute: typeof AuthenticatedRecurrencesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedBudgetsIdRoute: typeof AuthenticatedBudgetsIdRoute
  AuthenticatedFiscalConfiguracoesRoute: typeof AuthenticatedFiscalConfiguracoesRoute
  AuthenticatedFiscalNovaRoute: typeof AuthenticatedFiscalNovaRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedReportsClientesRoute: typeof AuthenticatedReportsClientesRoute
  AuthenticatedReportsConversaoRoute: typeof AuthenticatedReportsConversaoRoute
  AuthenticatedReportsFaturamentoRoute: typeof AuthenticatedReportsFaturamentoRoute
  AuthenticatedReportsFixosRoute: typeof AuthenticatedReportsFixosRoute
  AuthenticatedReportsFluxoRoute: typeof AuthenticatedReportsFluxoRoute
  AuthenticatedReportsInadimplenciaRoute: typeof AuthenticatedReportsInadimplenciaRoute
  AuthenticatedBudgetsIndexRoute: typeof AuthenticatedBudgetsIndexRoute
  AuthenticatedFiscalIndexRoute: typeof AuthenticatedFiscalIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvestmentsRoute: AuthenticatedInvestmentsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRoute,
  AuthenticatedRecurrencesRoute: AuthenticatedRecurrencesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedBudgetsIdRoute: AuthenticatedBudgetsIdRoute,
  AuthenticatedFiscalConfiguracoesRoute: AuthenticatedFiscalConfiguracoesRoute,
  AuthenticatedFiscalNovaRoute: AuthenticatedFiscalNovaRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedReportsClientesRoute: AuthenticatedReportsClientesRoute,
  AuthenticatedReportsConversaoRoute: AuthenticatedReportsConversaoRoute,
  AuthenticatedReportsFaturamentoRoute: AuthenticatedReportsFaturamentoRoute,
  AuthenticatedReportsFixosRoute: AuthenticatedReportsFixosRoute,
  AuthenticatedReportsFluxoRoute: AuthenticatedReportsFluxoRoute,
  AuthenticatedReportsInadimplenciaRoute:
    AuthenticatedReportsInadimplenciaRoute,
  AuthenticatedBudgetsIndexRoute: AuthenticatedBudgetsIndexRoute,
  AuthenticatedFiscalIndexRoute: AuthenticatedFiscalIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicNotaasWebhookRoute: ApiPublicNotaasWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
